In [1]:
import os
import pandas as pd

In [5]:
csv = pd.read_csv("./nonfinancial.csv") # Load our list of nonfinancial features we wanted. (I further cleaned the list up to only include a commodity. So I also removed swaps and forwards and index.)
data_dir = "C://Users/alexb/Documents/class/project3data/dump/"
 # path to where the csvs are. This could also be a quandl qu
files = os.listdir(data_dir)
lists = []
tkr_code = (csv["Quandl Code"]).values
code = []
count = 1
#makes a list of just the codes
while count < 205:
    count += 1
    code.append(tkr_code[count][6:])

In [10]:
file_list = []
count = 0
valid_code= []
big_df = pd.DataFrame()
#finds everything that we had in both lists
while count < 203:
    count += 1
    if (any(code[count] in item for item in files) == True):
        valid_code.append(code[count])
    else:
        print(code[count])

ODE_RS
MCX_STLRPR
ODE_AB
MCX_GRM
MCX_GRS
ASX_GW

In [11]:
count = 0
final_df = pd.DataFrame()
while count < (len(valid_code)-1):
    count +=1
    try:
        df =pd.read_csv(data_dir+valid_code[count]+"1.csv")
        df = df[["Date", "Settle", "Volume"]]
        df = df.rename(columns={"Settle": valid_code[count]+"S", "Volume": valid_code[count]+"V", "Date": valid_code[count]+"D"})
        final_df = pd.concat([final_df, df], axis=1)
    except:
        print(f"{valid_code[count]} not added")

ODE_SB not added
MCX_SI not added
MCX_SIM not added
ODE_TR not added
ASX_UB not added
ASX_US not added
ASX_VC not added
ASX_VW not added
ASX_WK not added
ODE_YC not added
MCX_ZN not added
MCX_ZNM not added
MCX_AG not added
MCX_AGM not added
MCX_AL not added
MCX_ALM not added
MCX_B not added
MCX_CL not added
MCX_CRDM not added
MCX_CT not added
MCX_CU not added
MCX_CUM not added
ODE_FS not added
MCX_GC not added
MCX_GD not added
MCX_GG not added
MCX_GM not added
MCX_GP not added
MCX_KP not added
MCX_KPK not added

In [19]:
final_df.to_csv("features.csv")

In [14]:
final_df.describe()

,CME_QXS,CME_QXV,LIFFE_RS,LIFFE_RV,SHFE_RBS,SHFE_RBV,CME_RBS,CME_RBV,LIFFE_RCS,LIFFE_RCV,...,CME_MCCS,CME_MCCV,CME_MES,CME_MEV,CME_MEOS,CME_MEOV,CME_MFS,CME_MFV,CME_MFFS,CME_MFFV
count,1199.000000,1199.000000,2924.000000,2899.000000,1347.000000,1330.000000,3409.000000,3409.000000,6231.000000,6151.000000,...,1191.000000,1191.000000,1286.000000,1286.000000,1292.000000,1292.000000,1287.000000,1287.000000,1300.000000,1300.000000
mean,52.925521,2.759800,119.113064,96770.256295,3102.659985,14127.610526,2.137587,43319.093282,1594.108337,2500.571940,...,50.799958,0.642317,1.021322,15.200622,615.203285,20.414087,52.517708,1.382284,75.596623,28.773077
std,10.665238,11.669518,6.106838,85666.823883,844.527759,50848.826469,0.597415,21825.989590,623.717663,3659.781146,...,7.960243,4.234078,38.600851,415.879985,167.689730,79.957064,18.842321,23.770774,16.533068,64.020758
min,0.000000,0.000000,103.430000,0.000000,1580.000000,0.000000,0.792700,0.000000,96.940000,0.000000,...,36.450000,0.000000,-0.216700,0.000000,0.000000,0.000000,0.000000,0.000000,49.300000,0.000000
25%,44.190000,0.000000,115.327500,4518.500000,2292.500000,62.000000,1.622200,27945.000000,1220.500000,88.500000,...,45.525000,0.000000,-0.121200,0.000000,501.587000,0.000000,38.300000,0.000000,61.600000,0.000000
50%,54.300000,0.000000,119.600000,98713.000000,3202.000000,300.000000,2.053000,42376.000000,1650.000000,938.000000,...,51.900000,0.000000,-0.087050,0.000000,573.036000,0.000000,48.790000,0.000000,75.000000,0.000000
75%,60.265000,0.000000,123.262500,151040.000000,3813.500000,1569.000000,2.676400,58283.000000,1982.500000,3801.000000,...,56.000000,0.000000,-0.034300,0.000000,698.906000,0.000000,63.960000,0.000000,91.300000,25.000000
max,78.050000,170.000000,133.300000,649939.000000,4780.000000,689884.000000,3.571000,173753.000000,4263.000000,54775.000000,...,76.750000,90.000000,1384.200000,14821.000000,1039.561000,884.000000,93.250000,551.000000,109.050000,840.000000

In [21]:
final_df

           CME_WD  CME_WS   CME_WV
0      2019-05-01  425.00    849.0
1      2019-04-30  418.50   5053.0
2      2019-04-29  426.75  30163.0
3      2019-04-26  435.00  29244.0
4      2019-04-25  434.75  33953.0
5      2019-04-24  432.25  34496.0
6      2019-04-23  438.75  44589.0
7      2019-04-22  435.75  36282.0
8      2019-04-18  444.25  42238.0
9      2019-04-17  447.00  40645.0
10     2019-04-16  445.00  87264.0
11     2019-04-15  459.50  76982.0
12     2019-04-12  464.50  62724.0
13     2019-04-11  460.50  73914.0
14     2019-04-10  458.00  59642.0
15     2019-04-09  459.50  79734.0
16     2019-04-08  465.25  77349.0
17     2019-04-05  467.75  83156.0
18     2019-04-04  470.75  67792.0
19     2019-04-03  471.00  59353.0
20     2019-04-02  464.00  45376.0
21     2019-04-01  462.75  58685.0
22     2019-03-29  457.75  69561.0
23     2019-03-28  464.50  47846.0
24     2019-03-27  469.50  58676.0
25     2019-03-26  469.25  81580.0
26     2019-03-25  469.50  56185.0
27     2019-03-22  466.00  68775.0
28     2019-03-21  466.50  56559.0
29     2019-03-20  464.75  52588.0
...           ...     ...      ...
15042  1959-08-12  195.40   4377.0
15043  1959-08-11  196.00   3352.0
15044  1959-08-10  195.50   3128.0
15045  1959-08-07  195.30   4515.0
15046  1959-08-06  195.30   3380.0
15047  1959-08-05  195.60   5619.0
15048  1959-08-04  196.70   3259.0
15049  1959-08-03  195.60   4554.0
15050  1959-07-31  196.20   2691.0
15051  1959-07-30  195.00   2835.0
15052  1959-07-29  194.50   3632.0
15053  1959-07-28  194.50   3683.0
15054  1959-07-27  195.30   3776.0
15055  1959-07-24  194.40   3079.0
15056  1959-07-23  194.20   2549.0
15057  1959-07-22  194.50   3397.0
15058  1959-07-21  194.70   4055.0
15059  1959-07-20  195.40   4415.0
15060  1959-07-17  194.40   3045.0
15061  1959-07-16  195.10   3485.0
15062  1959-07-15  195.30   3761.0
15063  1959-07-14  195.50   3489.0
15064  1959-07-13  196.10   4426.0
15065  1959-07-10  195.60   4734.0
15066  1959-07-09  195.50   4949.0
15067  1959-07-08  196.40   4538.0
15068  1959-07-07  197.10   5604.0
15069  1959-07-06  197.00   6591.0
15070  1959-07-02  197.10   4780.0
15071  1959-07-01  196.40   5828.0

[15072 rows x 3 columns]

In [18]:
df1 = final_df[final_df.isna().any(axis=1)]
final_df

,CME_QXD,CME_QXS,CME_QXV,LIFFE_RD,LIFFE_RS,LIFFE_RV,SHFE_RBD,SHFE_RBS,SHFE_RBV,CME_RBD,...,CME_MEV,CME_MEOD,CME_MEOS,CME_MEOV,CME_MFD,CME_MFS,CME_MFV,CME_MFFD,CME_MFFS,CME_MFFV
0,2018-11-27,77.68,0.0,2019-05-01,127.61,88149.0,2019-04-30,4192.0,143910.0,2019-05-01,...,0.0,2019-05-01,684.125,0.0,2019-05-01,66.05,0.0,2019-05-01,71.60,0.0
1,2018-11-26,77.68,0.0,2019-04-30,127.32,214495.0,2019-04-29,4179.0,86764.0,2019-04-30,...,0.0,2019-04-30,684.125,0.0,2019-04-30,66.04,0.0,2019-04-30,68.58,0.0
2,2018-11-23,77.55,0.0,2019-04-29,127.67,111667.0,2019-04-26,4145.0,78638.0,2019-04-29,...,0.0,2019-04-29,683.631,0.0,2019-04-29,66.04,0.0,2019-04-29,68.58,0.0
3,2018-11-21,77.55,0.0,2019-04-26,127.75,133857.0,2019-04-25,4143.0,96228.0,2019-04-26,...,0.0,2019-04-26,684.079,0.0,2019-04-26,66.01,0.0,2019-04-26,68.60,0.0
4,2018-11-20,77.55,0.0,2019-04-25,127.62,126012.0,2019-04-24,4135.0,130212.0,2019-04-25,...,0.0,2019-04-25,684.730,0.0,2019-04-24,66.29,0.0,2019-04-25,69.25,0.0
5,2018-11-19,77.55,0.0,2019-04-24,127.45,155691.0,2019-04-23,4157.0,113374.0,2019-04-24,...,0.0,2019-04-24,685.383,0.0,2019-04-23,65.99,0.0,2019-04-24,69.15,0.0
6,2018-11-16,77.55,0.0,2019-04-23,126.84,131453.0,2019-04-22,4156.0,278732.0,2019-04-23,...,0.0,2019-04-23,685.909,0.0,2019-04-22,65.88,0.0,2019-04-23,69.35,0.0
7,2018-11-15,77.55,0.0,2019-04-22,127.14,NaN,2019-04-19,4108.0,213916.0,2019-04-22,...,0.0,2019-04-22,687.213,0.0,2019-04-18,65.34,0.0,2019-04-22,69.20,0.0
8,2018-11-14,77.55,0.0,2019-04-18,127.14,143943.0,2019-04-18,4122.0,338660.0,2019-04-18,...,0.0,2019-04-18,681.167,0.0,2019-04-17,65.33,0.0,2019-04-18,69.20,0.0
9,2018-11-13,77.55,0.0,2019-04-17,126.67,167549.0,2019-04-17,4152.0,315588.0,2019-04-17,...,0.0,2019-04-17,678.832,0.0,2019-04-16,65.30,0.0,2019-04-17,69.40,0.0
10,2018-11-12,77.55,0.0,2019-04-16,126.88,203909.0,2019-04-16,4150.0,328294.0,2019-04-16,...,0.0,2019-04-16,679.490,0.0,2019-04-15,65.42,0.0,2019-04-16,69.10,0.0
11,2018-11-09,77.55,0.0,2019-04-15,126.85,174898.0,2019-04-15,4144.0,474656.0,2019-04-15,...,0.0,2019-04-15,678.114,0.0,2019-04-12,65.80,0.0,2019-04-15,69.00,5.0
12,2018-11-08,77.55,0.0,2019-04-12,126.89,179797.0,2019-04-12,4120.0,120.0,2019-04-12,...,0.0,2019-04-12,682.539,0.0,2019-04-11,65.54,0.0,2019-04-12,69.75,0.0
13,2018-11-07,78.05,0.0,2019-04-11,127.66,142451.0,2019-04-11,4019.0,0.0,2019-04-11,...,0.0,2019-04-11,680.162,0.0,2019-04-10,65.74,0.0,2019-04-11,70.00,0.0
14,2018-11-06,78.05,0.0,2019-04-10,128.30,129770.0,2019-04-10,4019.0,120.0,2019-04-10,...,0.0,2019-04-10,684.161,0.0,2019-04-09,65.23,0.0,2019-04-10,70.45,0.0
15,2018-11-05,78.05,0.0,2019-04-09,128.11,165645.0,2019-04-09,4007.0,0.0,2019-04-09,...,0.0,2019-04-09,669.570,0.0,2019-04-08,66.03,0.0,2019-04-09,71.00,25.0
16,2018-11-02,78.00,0.0,2019-04-08,128.12,108591.0,2019-04-08,4007.0,60.0,2019-04-08,...,0.0,2019-04-08,667.565,0.0,2019-04-05,65.18,0.0,2019-04-08,70.50,15.0
17,2018-11-01,77.50,0.0,2019-04-05,128.01,151570.0,2019-04-04,3841.0,60.0,2019-04-05,...,0.0,2019-04-05,663.394,0.0,2019-04-04,64.40,18.0,2019-04-05,69.65,30.0
18,2018-10-31,77.50,0.0,2019-04-04,128.35,135930.0,2019-04-03,3869.0,300.0,2019-04-04,...,0.0,2019-04-04,656.564,0.0,2019-04-03,64.92,100.0,2019-04-04,68.45,0.0
19,2018-10-30,77.50,0.0,2019-04-03,128.47,199069.0,2019-04-02,3813.0,0.0,2019-04-03,...,0.0,2019-04-03,659.034,0.0,2019-04-02,63.99,0.0,2019-04-03,66.60,55.0
20,2018-10-29,76.89,0.0,2019-04-02,129.33,185229.0,2019-04-01,3800.0,60.0,2019-04-02,...,0.0,2019-04-02,584.536,0.0,2019-04-01,63.99,0.0,2019-04-02,75.44,0.0
21,2018-10-26,76.89,0.0,2019-04-01,128.86,145788.0,2019-03-29,3732.0,254.0,2019-04-01,...,0.0,2019-04-01,584.536,0.0,2019-03-29,63.98,0.0,2019-04-01,75.44,0.0
22,2018-10-25,77.45,0.0,2019-03-29,129.37,208374.0,2019-03-28,3721.0,872.0,2019-03-29,...,0.0,2019-03-29,584.536,0.0,2019-03-28,63.94,0.0,2019-03-29,75.45,0.0
23,2018-10-24,77.45,0.0,2019-03-28,129.28,170976.0,2019-03-27,3724.0,96.0,2019-03-28,...,0.0,2019-03-28,583.533,0.0,2019-03-27,63.95,0.0,2019-03-28,77.15,0.0
24,2018-10-23,77.35,0.0,2019-03-27,129.34,221141.0,2019-03-26,3702.0,246.0,2019-03-27,...,0.0,2019-03-27,584.239,0.0,2019-03-26,63.89,0.0,2019-03-27,77.30,0.0
25,2018-10-22,77.35,0.0,2019-03-26,125.77,350.0,2019-03-25,3749.0,304.0,2019-03-26,...,0.0,2019-03-26,584.966,0.0,2019-03-25,63.67,0.0,2019-03-26,77.20,0.0
26,2018-10-19,77.35,0.0,2019-03-25,125.98,212.0,2019-03-22,3778.0,62.0,2019-03-25,...,0.0,2019-03-25,585.014,0.0,2019-03-22,63.59,0.0,2019-03-25,77.40,0.0
27,2018-10-18,77.10,0.0,2019-03-22,125.75,374.0,2019-03-21,3812.0,120.0,2019-03-22,...,0.0,2019-03-22,583.359,0.0,2019-03-21,63.90,0.0,2019-03-22,77.35,0.0
28,2018-10-17,77.10,0.0,2019-03-21,125.34,1705.0,2019-03-20,3802.0,260.0,2019-03-21,...,0.0,2019-03-21,580.252,0.0,2019-03-20,64.11,0.0,2019-03-21,77.55,0.0
29,2018-10-16,77.10,0.0,2019-03-20,124.53,1834.0,2019-03-19,3807.0,356.0,2019-03-20,...,0.0,2019-03-20,579.658,0.0,2019-03-19,63.89,0.0,2019-03-20,77.95,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15042,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15043,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15044,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15045,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15046,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15047,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15048,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15049,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15050,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15051,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15052,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15053,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15054,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15055,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15056,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15057,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15058,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15059,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15060,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15061,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15062,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15063,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15064,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15065,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15066,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15067,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15068,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15069,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15070,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15071,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN